import { Sidebar, SidebarContent } from "@/components/layouts/sidebar";
import { Topbar } from "@/components/layouts/topbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex min-h-screen w-full p-2 gap-2">
      <Sidebar />
      <SidebarContent>
        <div className="min-h-[calc(100vh-1rem)] container mx-auto space-y-2">
          <Topbar />
          <div className="p-2">{children}</div>
        </div>
      </SidebarContent>
    </main>
  );
}
